apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-deployment
  labels:
    app: sensors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sensors
  template:
    metadata:
      labels:
        app: sensors
    spec:
      containers:
      - name: sensors
        image: wwwWWWwwwtch/sensors:latest
        ports:
        - containerPort: 8090
