name: Deploy

on:
    push:
        branches: [main]

jobs:
    test-application:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            
            - uses: docker-practice/actions-setup-docker@master 
            
            - uses: azure/setup-kubectl@v3
            
            - name: Run Add Test
              working-directory: ./
              run: |
                  docker build . -t wwwwwwwwwtch/sensors:latest
                  docker login -u wwwwwwwwwtch -p 1qaz1qaz1qaz 
                  docker image ls
                  docker push m3r1/testcd:latest
                  sudo mkdir -p /root/.kube/
                  sudo mv ./kubeconfig /root/.kube/config
                  sudo kubectl apply -f deployment.yml
